name: Bump versions

on:
  workflow_dispatch:
    inputs:
      version:
        description: The version to bump to
        required: true

      branch:
        description: Bump a specific branch. If blank, the default master/main branch will be used
        default: ''

jobs:
  bump-versions:
    runs-on: ubuntu-latest
    steps:
      - name: Bump versions
        uses: Frejdh/action-bump-version@master
        with:
          version: ${{ inputs.version }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          repository:  ${{ inputs.repository || '' }}
          branch:  ${{ inputs.branch }}
