name: Pull Request Build

env:
  DEFAULT_GIT_REF: 'ERROR: missing branch specifier'

on:
  pull_request:
  workflow_dispatch:
    inputs:
      ref:
        description: Git reference (branch/commit)
        required: true

jobs:
  build_and_test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]
    steps:
      - name: Build and test code for branch '${{ github.event.pull_request.head.ref || github.event.inputs.ref || env.DEFAULT_GIT_REF }}'
        uses: Frejdh/action-build-and-test@v1.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          java-version: 17
          cache-id: v1
          commitish: "${{ github.event.pull_request.head.ref || github.event.inputs.ref || env.DEFAULT_GIT_REF }}"